### ISSUE TITLE
Add White Background for Unfilled Diagram Parts in Light Theme

### ISSUE THREAD

**Issue by zaakiy** [gitcpy/obsidian-diagram-popup#8]
Great plugin! thank you very much, because it's a life save for me to be able to zoom into big diagrams.

Please consider the image below, where the unfilled parts of the diagram are not white. In fact, it's slightly blurred and partially transparent.  Can you please consider making the background white for the light theme?

Thank you.

### Expected background appearance (without popup)
![image](https://github.com/user-attachments/assets/834dd913-25d5-4311-8659-219f66e27a52)

### Current background appearance (with popup)
![image](https://github.com/user-attachments/assets/1e395e9e-663f-4b86-9f55-d286ef6853e4)

**Comment by zaakiy** [comment]
Here is the sample mermaid diagram code

(please add "mermaid" after the backticks, I removed it so that the code will show in GitHub instead of the rendered diagram)

```
stateDiagram-v2
  classDef classNoUsage fill:orange,color:black,font-weight:bold,stroke-width:2px,stroke:black
	  classDef classFree fill:skyblue,color:black,font-weight:bold,stroke-width:2px,stroke:black
	  classDef classTrial fill:Gold,color:black,font-weight:bold,stroke-width:2px,stroke:black
	  classDef classActive fill:green,color:white,font-weight:bold,stroke-width:2px,stroke:black
	  classDef classAddCard fill:#E497E5,color:black,font-weight:bold,stroke-width:2px,stroke:black
	  classDef classRenew fill:#ff00ff,color:white,font-weight:bold,stroke-width:2px,stroke:black
	  
  
	  state "asdasdasdasd" as containerNoUsage {
			state joasdasdaage <<join>>
			state "asdasda" as noUsage
			joisde --> noUasdge : ❗casdge
			state leaasdage <<join>>
		}
	  [*] --> joinNoUsage : 🎬 On user insert, set<br>nasdasdus = free
	  
	  state lesdfsfdUp <<join>>
	  
  
	  state joisdfsd1 <<join>>
	  
	  joisdfsdf1 --> sdfsdfage
	  
  
	  state "Trsdfsfdsee" as containerFree {
			state josdfe <<join>>
			state lesdfe <<join>>
			state "Free<br>&nbsp;&nbsp;&nbsp;&nbsp; - set nsdfsdftus to trial" as free
			free --> free : cusdfsdfstatus <br> === free
			  
  
	  }
	  
```

**Comment by gitcpy** [comment]
Alright, I will add an option for your requestment. Give sometime.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-popup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 上午9:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gitcpy/obsidian-diagram-popup] Add White Background for Unfilled Diagram Parts in Light Theme (Issue #8)





 
Great plugin! thank you very much, because it's a life save for me to be able to zoom into big diagrams.
 
Please consider the image below, where the unfilled parts of the diagram are not white. In fact, it's slightly blurred and partially transparent.  Can you please consider making the background white for the light theme?
 
Thank you.
 
Expected background appearance (without popup)
 
image.png (view on web)
 
Current background appearance (with popup)
 
image.png (view on web)

**Comment by zaakiy** [comment]
Thanks, I can give it a try to change the CSS although I will need your help to test it

**Comment by zaakiy** [comment]
https://github.com/gitcpy/obsidian-diagram-popup/pull/9

**Comment by gitcpy** [comment]
> #9

Thank you very much! I did set the backaground untransparent. But I realize the UI background trend , in current devices，are mostly translucent like frosted glass. So I make it translucent. I am glad you have the same idea as what I thought. So I will make an option toggle it translucent or untranparent. And it will fit the trend and the requestment from you and me. If you have any idea, just let me know. Thanks again.!

**Comment by gitcpy** [comment]
![bg-setting](https://github.com/user-attachments/assets/a82b79c8-7cc4-4cdb-b646-939a2c05eaf5)
I added two settings for you.
Try it.
Thanks your feedback and your work!

**Comment by zaakiy** [comment]
> I added two settings for you.

Looks amazing, thank you!
